### PR TITLE
within safely(), passes `quiet` to capture_error()

### PR DESCRIPTION
**Pull request by ijlyttle**
addresses #296

### CODE REVIEW

**Comment by hadley** [comment]
Thanks! Can you please add a bullet to NEWS?

**Comment by ijlyttle** [comment]
No problem, added bullet to NEWS.

**Comment by hadley** [comment]
Thanks - in the future, please remember to include `fixes #xxx` in on of the commit messages so the corresponding issue is automatically closed when the PR is merged

**Comment by ijlyttle** [comment]
Will do!

**Pull request merged**
