### PR TITLE
Rename zip() to zip_n()

### PR DESCRIPTION
**Pull request by lionel-**
And provide shortcuts `zip2()` and `zip3()`.

### CODE REVIEW

**Comment by lionel-** [comment]
Added the integer coercion.

**Comment by lionel-** [comment]
by the way, in objects.R we have `is_numeric()` and `is_bare_numeric()` but no `_double` version. To be consistent we should either change the predicates to doubles or change `map_dbl()` to `map_num()`. I think I prefer the latter because the suffix is pronounced as one syllable instead of two.

**Comment by hadley** [comment]
I prefer double because it's less overloaded than numeric (which sometimes means int or double)

**Comment by lionel-** [comment]
voilà

**Comment by lionel-** [comment]
Fixed the conflict and added all the new functions to the README. We come a long way :)

**Comment by lionel-** [comment]
by the way, I know I came up with the idea for purr, but I think I prefer the original name lowliner. It's catchy and it looks serious. The only downside is that it's a bit longer so namespaced calls will be a bit longer too, e.g. `lowliner::map_if(x, p, f)`. But to me this looks much better in my code than `purrr::map_if(x, p, f)`, perhaps in part because all those `rrr` look very blurry to me (but maybe that's just me). Purr is also a word that I find harder to pronounce.

lowliner could refer to the fact that this package is a "better standard library" with underscored function names. But it doesn't need to refer to anything really, I mean, underscore.js doesn't really have a justification (or does it? I'm not aware of any).

**Comment by hadley** [comment]
Thanks!

I'm pretty happy with purrr as a name - I like the play on pure R.

**Pull request merged**
