### PR TITLE
Implement flatten_margin() and enlist_margin()

### PR DESCRIPTION
**Pull request by lionel-**
As per #66.

`enlist_margin()` may need a better name to reflect the hierarchical output it produces.
Oh, what about `branch_margin()`?

### CODE REVIEW

**Comment by hadley** [comment]
I feel like maybe `array_margin()` and `array_list()` might be more evocative names?

**Comment by lionel-** [comment]
at first I had to think a bit about what they mean but now that I get it they make sense.

The downside is that they are not verbs. On the other hand many object constructors are not verbs, so we can indeed think of them not as actions on arrays but as constructors.

though I feel
```r
obj %>% array_list(c(3, 1))
```
is not as expressive as
```r
obj %>% branch_margin(c(3, 1))
```

I think I would prefer this one, and then rename `flatten_margin()` to `enlist_margin()` which makes more sense, especially with regard to the other `enlist()` function.

Of course the decision is yours.

**Comment by hadley** [comment]
When I read `branch_margin()` I have no idea what it does - could you give a bit more detail about why you think `branch()` is the natural verb?

**Comment by lionel-** [comment]
because it creates a tree of lists based on the margin. But maybe `branch` reflects more the idea of one fork than of a whole tree indeed

**Comment by hadley** [comment]
What about `array_branch()` (instead of `enlist_array()`) and `array_tree()` instead of `branch_array()`?

**Comment by lionel-** [comment]
I think that looks good :-)

**Comment by lionel-** [comment]
Here you go. Love these function names!

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
